### ISSUE TITLE
need to fix 

### ISSUE THREAD

**Issue by Hamood111** [AndroPlus-org/magisk-module-miui-cn2global#10]
the module exposed Found files modified by Magisk modules need to fix# plus the Arabic language make battery percentage icon upside down need to fix# also I hope u add Arabic language with English numbers in the future 👍

**Comment by AndroPlus-org** [comment]
Battery percentage icon is controlled by MIUI and I don't know how to fix.

Which one is "Arabic language with English numbers"?
Here's the list of languages in official global ROM and if it's not included, I can't add it.
![Screenshot_2023-05-18-08-29-17-622_com android settings](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/4242402/d8a5d0cd-a985-41a8-b3d4-e31619aa02c3)

**Comment by Hamood111** [comment]
> Battery percentage icon is controlled by MIUI and I don't know how to fix.
> 
> Which one is "Arabic language with English numbers"? Here's the list of languages in official global ROM and if it's not included, I can't add it. ![Screenshot_2023-05-18-08-29-17-622_com android settings](https://user-images.githubusercontent.com/4242402/239099225-d8a5d0cd-a985-41a8-b3d4-e31619aa02c3.jpg)

first of all thank you for response you are one of your kind not like many other creators the global ROM don't make icon upside down in arab language and the one comes with English numbers it's العربية ( الأرقام الغربية ) I hope u add in new update and even if u didn't I still appreciate your work peace and love

**Comment by Hamood111** [comment]
> 

![Screenshot_2023-05-21-15-51-59-145-edit_com brave browser](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/116981650/f70c6f4b-04f2-481a-96a3-6c62ce2cd0d4)

**Comment by Atarpara** [comment]
This module is detected by root detector even this app is in Denylist due to this some banking application not working.
![Screenshot_2023-05-27-14-36-16-699_com.godevelopers.OprekCek.jpg](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/66815072/9655e391-149b-46c9-957d-500331644f05)

**Comment by AndroPlus-org** [comment]
It looks like Xiaomi uses special format (not in AOSP) and it causes error when I build module with it... 
Please try this adb command instead:
adb shell
settings put system system_locales ar-EG-u-nu-latn

and reboot.

For the banking app, is it really detects module?
Denylist isn't Magisk Hide so you have to use Shamiko magisk module.
Download and install it from here, and uncheck "Enforce DenyList" in Magisk app (Shamiko uses denylist to select which app to enable, but "Enforce DenyList" isn't needed for Shamiko).
https://github.com/LSPosed/LSPosed.github.io/releases

**Comment by Atarpara** [comment]
> It looks like Xiaomi uses special format (not in AOSP) and it causes error when I build module with it... 
> Please try this adb command instead:
> adb shell
> settings put system system_locales ar-EG-u-nu-latn
> 
> and reboot.
> 
> For the banking app, is it really detects module?
> Denylist isn't Magisk Hide so you have to use Shamiko magisk module.
> Download and install it from here, and uncheck "Enforce DenyList" in Magisk app (Shamiko uses denylist to select which app to enable, but "Enforce DenyList" isn't needed for Shamiko).
> https://github.com/LSPosed/LSPosed.github.io/releases

Actually I tried with shamiko and same issues facing with momo. Once I uninstalled this module momo and oprek detector successfully passed. This problem occurs only this module I have installed other module like safety-net, etc.

**Comment by bouyhy1989** [comment]
Arigato hozaymas for you hard work , i rally appreciate it , i have some questions , is ok google working with that module in miui14 and how about notifications ?  I dont get call notifications on whatsapp neither facebook messenger even after enabling autostart and disabling miui battery saver  and granted all the permissions , thank you a lot again , cheers from Paris France

**Comment by Hamood111** [comment]
this is my comment and my question u are using the wrong place to show your problems + this module for multi languages so your MIUI Chinese rom become supposed all languages and it's have no relation with your other issues like notification social media apps and battery issues ok there's something name new issue press on it and make your own and I will close mine

**Comment by bouyhy1989** [comment]
آسف حبيبي سوف  اطرح تساؤلي .تحياتي  sorry bro im gonna open a new request .cheers

**Comment by Hamood111** [comment]
it's okay nevermind bro I'm just telling you're in the wrong section, Salut
