### ISSUE TITLE
Update module in magisk

### ISSUE THREAD

**Issue by KimPig** [AndroPlus-org/magisk-module-miui-cn2global#2]
Hello. Thank you for developing a cool module. One inconvenience is that whenever there is an update, it is inconvenient to come into github and update it. Can you make it possible to update within the Magisk app like LSPosed?

**Comment by AndroPlus-org** [comment]
I thought I added update function but I forgot to enable it...
Fixed in 3ce4ca0 and reuploaded v10 zip with it.
If you reinstall new v10 zip, you'll receive update in the future.
