### ISSUE TITLE
[Not a bug] About these .apk file in the module and ask for permission

### ISSUE THREAD

**Issue by WeiguangTWK** [AndroPlus-org/magisk-module-miui-cn2global#23]
I am about to integrate your module into modified HyperOS CN to enable user to use their language without Magisk module, before that may I ask how you made these treble-overlay-xxxxxx.apk file?

And also I am asking for your permission to integrate this module in our ROM, we will specify the author and source URL of this module

**Comment by AndroPlus-org** [comment]
OK.

**Comment by WeiguangTWK** [comment]
> OK.

Thank you very much! So as for these overlay apks could you tell me something about that?

**Comment by AndroPlus-org** [comment]
To make overlay files, I used apktool and xmlstarlet command to unpack apks (manually extracted from global rom) and copy strings to overlay's strings.xml, then build them.
There will be build error if there's non-existing en-US strings so I also use "android-localization-helper" to clean copied strings.xml:
https://pypi.org/project/android-localization-helper/

**Comment by WeiguangTWK** [comment]
Got it. Thank you again for your generous help!

**Comment by WeiguangTWK** [comment]
@AndroPlus-org  Sorry to disturb again. I still have a question: Which app source you use? 

I find [here](https://github.com/phhusson/OverlayMaker)  according package name from your module but when I completed the string.xml stuff and build, I find the size of the apk file is quite bigger (about 8MB).

I try to compare apk content of yours and mine one and find sth like dex file is not present, so you remove java code before compile or remove files and repack apk?

Thank you again for your patience

**Comment by AndroPlus-org** [comment]
I'm using this one as a base:
https://github.com/phhusson/vendor_hardware_overlay
The vendor_hardware_overlay is originally used for overwriting config.xml or something, but overlay can overwrite strings.xml too.
I'm copying localization strings from apks from the latest Global ROM to overlay's strings.xml then build them all.
