### ISSUE TITLE
a suggestion 

### ISSUE THREAD

**Issue by mohsen59** [AndroPlus-org/magisk-module-miui-cn2global#4]
Hi. Thank you for this great work. There is a "Persian" 
or "Arabic" languages, but it is not "Persian with western numbers" or "Arabic" with western numbers,  which is very useful. Can you add this option in the next update? 🙏🙏

**Comment by AndroPlus-org** [comment]
Is it included in official MIUI Global version?
If so I can add it.

**Comment by Hamood111** [comment]
first of all I wanna say thank you for this magnificent module but I wish if you added Arabic language with English numbers also there is a problem with charge percentage animation it's upside down you need to fixed ✌️
