### ISSUE TITLE
Not working on MIUI Beta Latest build

### ISSUE THREAD

**Issue by atarpara** [AndroPlus-org/magisk-module-miui-cn2global#5]
I am using V13 module since 1 month but it suddenly stopped after the recent update. 

Device Name: Alioth
MIUI version: V14.0.23.3.13 DEV
Magisk Version: magisk canary(25210)

[magisk_log_2023-03-21T10.56.22.log](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/files/11025212/magisk_log_2023-03-21T10.56.22.log)

**Comment by AndroPlus-org** [comment]
Please try downgrading Magisk to 25209.
https://github.com/topjohnwu/magisk-files/commit/0b9eca062198e568f9cc101eaf64bb5d9edb8a34

25210 has problem of module loading, but there's no canary update after the fix.
https://github.com/topjohnwu/Magisk/issues/6688

**Comment by atarpara** [comment]
Downgrade to magisk 25206 but still it's not working.

**Comment by AndroPlus-org** [comment]
25206 has another bug with overlayfs (can't replace some files in system), so please use 25209.
