### ISSUE TITLE
Ask for only Nearby Share & Location History

### ISSUE THREAD

**Issue by KevinNitroG** [AndroPlus-org/magisk-module-miui-cn2global#6]
It is great to have only Nearby Share & Location History without multi languages module ♥️. Can you add options to choose when install the module?

**Comment by AndroPlus-org** [comment]
OK, I added:
[magisk-module-miui-cn2global-no-languages.zip](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/releases/download/v13/magisk-module-miui-cn2global-no-languages.zip)
