### ISSUE TITLE
[Feature request] Swipe up from corner for Google Assistant

### ISSUE THREAD

**Issue by turbo-boo** [AndroPlus-org/magisk-module-miui-cn2global#7]
いつもモジュールを使用させていただいています。
cn版を使っている際に、よくミスしてGoogle Assistantが出てしまうのでこの設定のスイッチを追加していただくことは出来ますか？グローバル版やeu版にはあるのですが、cn版には無いのでもし可能であればお願いします🙇 
全画面表示(Full screen display)のページの上から三番目にある設定です。

**Comment by AndroPlus-org** [comment]
追加できるか調べてみます。

**Comment by AndroPlus-org** [comment]
Activity Launcherなどで「ジェスチャーナビゲーションの感度」ページを開くとオプションがあることは確認できました。
ただ、Xiaomi 13 Ultraグローバル版などではオフにする機能自体が削除されているようで、動作しませんでした。
旧機種であれば上記ページを開いてオフにできるかもしれません。

**Comment by turbo-boo** [comment]
> Activity Launcherなどで「ジェスチャーナビゲーションの感度」ページを開くとオプションがあることは確認できました。 ただ、Xiaomi 13 Ultraグローバル版などではオフにする機能自体が削除されているようで、動作しませんでした。 旧機種であれば上記ページを開いてオフにできるかもしれません。

無効化できました！ありがとうございますm(_ _)m
