### ISSUE TITLE
How to gt started? 

### ISSUE THREAD

**Issue by Dirkkro** [AndroPlus-org/magisk-module-miui-cn2global#8]
Maybe  a short introduction of the magisk main module would be helpful. 
1. I searched in Google Play, but was not sucsessful, got several  Magisk Tools, but seems to be  boatware :( maybe a hint where to find the real one?
2. Is a rooted phone needed to run the magisk Modules?

**Comment by AndroPlus-org** [comment]
The only legit source is topjohnwu's GitHub:
https://topjohnwu.github.io/Magisk/install.html

This module only works on the rooted device.
