### ISSUE TITLE
some application on miui 14 cant be translate?

### ISSUE THREAD

**Issue by Boy656** [AndroPlus-org/magisk-module-miui-cn2global#9]
hello these application still not translated on miui 14 china i am using arabic language 
1-com.android.mms
2-com.miui.securitycenter
3-com.android.thememanager
4-com.miui.player
5-com.android.calendar
6-com.miui.contentextension
and these pictures of them👇🏻
![Screenshot_٢٠٢٣-٠٥-١٢-١٥-٣٥-٤٧-٤٣٨_com android mms](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/69907104/51ba550d-a3c2-4a84-bde5-0c6b194e136e)
![Screenshot_٢٠٢٣-٠٥-١٢-١٥-٣٥-٥٥-١٤٨_com android mms](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/69907104/aaaf3ffc-35ec-44c0-ab1a-bdbacffe3b2f)
![Screenshot_٢٠٢٣-٠٥-١٢-١٥-٣٦-٤٥-٩٠٥_com android calendar](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/69907104/dd093ef9-413c-4efd-a858-cd28503ec53b)
![IMG_٢٠٢٣٠٥١٢_١٥٤٠٠٩](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/69907104/6055ab60-fa62-4c3b-9ce4-07781486743d)
![IMG_٢٠٢٣٠٥١٢_١٥٤٠٥٤](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/69907104/c8827cf3-b605-4e5d-ab35-b81d28ba284d)
![IMG_٢٠٢٣٠٥١٢_١٥٤١٢٦](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/69907104/4a5f5197-1793-4ef9-a75d-515dd9ac5a94)
![IMG_٢٠٢٣٠٥١٢_١٥٤١٥٨](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/69907104/1b201b16-d7f2-4197-a7d0-f744d9d1b731)
![Screenshot_٢٠٢٣-٠٥-١٢-١٥-٤٢-٢٦-٤٤٦_com miui contentextension](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/69907104/4e4b8a33-a23a-4003-bf76-086378d33d6d)
![Screenshot_٢٠٢٣-٠٥-١٢-١٥-٤٥-٢٧-٧٥٩_com miui securitycenter](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/69907104/c1f40b00-44c2-49e0-b4e5-0d3d9c2d97e2)
![Screenshot_٢٠٢٣-٠٥-١٢-١٥-٤٦-٢٧-٢٧٨_com miui securitycenter](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/69907104/2ebe7d78-e0fe-4365-8366-d4520895cc80)
![Screenshot_٢٠٢٣-٠٥-١٢-١٥-٤٦-٥٥-٠٤٩_com miui securitycenter](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/69907104/2a05f4ff-8f4b-4944-86fa-1016fa0f4432)

**Comment by Boy656** [comment]
![Screenshot_٢٠٢٣-٠٥-١٢-١٥-٥٢-٢٩-٨٠٩_com android settings](https://github.com/AndroPlus-org/magisk-module-miui-cn2global/assets/69907104/012c6439-5e11-4e57-b2cc-c8f5a948ab4f)
this picture about the language

**Comment by AndroPlus-org** [comment]
Some of them are included in global rom so I'll try to add them.
It's low priority for me since there's no donations though.

**Comment by Boy656** [comment]
thanks bro and sorry for bother
.
Please do it when you have free time or when you are preparing for the release of the next update, and thank you brother for making this module
